### ISSUE TITLE
ncl fails to build with hdf 4.3.0

### ISSUE THREAD

**Issue by opoplawski** [NCAR/ncl#208]
**Describe the bug**

When building ncl 6.6.2 against hdf 4.3.0 I get:
```
gcc -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Wno-complain-wrong-lang -Werror=format-security -fpermissive -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -std=c99 -fPIC -fno-strict-aliasing -fopenmp -fcommon -DH5_USE_110_API   -I../../../.././include -I/usr/include/hdf -I/usr/include/netcdf -I/usr/include/udunits2 -I/usr/include/freetype2 -I/usr/include/gdal   -DBuildRasterHDF -DLINUX -DBuildRasterHPPCL -DBuildRasterNrif -DBuildRasterSun 		-DBuildRasterXWD  -DBuildRasterAVS -DBuildRasterSGI 		-DBuildRasterAbekas  -DBuildRasterBinary -DBuildRasterYUV 		-DNGTMPDIR='"tmp"' -Dx86_64 -DIBM -D_ISOC99_SOURCE -D_POSIX_SOURCE -D_XOPEN_SOURCE -DByteSwapped -DNeedFuncProto    -c -o hdf.o hdf.c
hdf.c:56:10: fatal error: dfgr.h: No such file or directory
   56 | #include <dfgr.h>
      |          ^~~~~~~~
compilation terminated.
```

As announced here: https://github.com/HDFGroup/hdf4/releases/tag/hdf4.3.0 hdf 4.3.0 drops many internal headers include apparently dfgr.h and dfi.h.

If I remove those includes it builds okay apparently without any new warnings that I've noticed, so apparently they are not really needed?

**Computing environment**
 - OS: Linux
 - OS version: Fedora Rahide
 - NCL Version:6.6.2
 - Installation method: building from source

**Comment by thebaptiste** [comment]
I have the same problem on rockylinux:8
A new release with this fix (if validated) would be great.

**Comment by Yiwei2020** [comment]
This is my fix:
sed -i 's/#include <dfi.h>/#include <df.h>/' ./ncl-6.6.2/ni/src/ncl/FileSupport.c
sed -i '\|^#include <dfgr.h>$|d' ./ncl-6.6.2/ncarview/src/lib/libncarg_ras/hdf.c
